name: 'cycloud-io/action-is-installed-xcode'
description: 'Checks to see if the same Xcode version as GitHub-hosted is installed'
author: 'whywaita'

branding:
  icon: "user-check"
  color: "white"

inputs:
  success-on-miss:
    description: 'If the Xcode version is not installed, the action will be successful'
    required: false
    default: false

runs:
  using: node20
  main: dist/main.js